name: znc-albaguirre
version: "1.6.6"
summary: an advanced IRC bouncer
description: |
 an advanced IRC bouncer that is left connected so an IRC client can
 disconnect/reconnect without losing the chat session.

grade: stable
confinement: strict

apps:
  znc:
    command: znc --datadir $SNAP_COMMON --allow-root --foreground
    plugs: [network, network-bind]
    daemon: simple

  make-config:
     command: znc --datadir $SNAP_COMMON --makeconf --foreground --allow-root
     plugs: [network, network-bind]

parts:
  znc:
    plugin: autotools
    source: https://github.com/znc/znc.git
    source-tag: znc-1.6.6
    configflags:
      - '--enable-python'
      - '--enable-perl'
      - '--prefix=/usr/'
    build-packages:
      - python3-dev
      - libperl-dev
      - swig
      - pkg-config
      - cmake
      - automake
      - autoconf
      - libssl-dev
      - libicu-dev
      - zlib1g-dev
    prepare: |
      patch -p1 < ../../../modules-dir-relative-snap-dir.patch

  znc-push:
    plugin: make
    source: https://github.com/jreese/znc-push.git
    after: [znc]
    build-packages:
      - ca-certificates
    build: |
      make
    install: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/lib/znc
      mv push.so $SNAPCRAFT_PART_INSTALL/usr/lib/znc
